---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
  labels:
    k8s-app: argo
    part-of: argo
data:
  config: |
    artifactRepository:
      s3:
        bucket: bucket
        endpoint: argo-minio.argo:9000
        insecure: true
        accessKeySecret:
          name: argo-minio
          key: accesskey
        secretKeySecret:
          name: argo-minio
          key: secretkey
    executor:
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 400m
          memory: 800Mi
