---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-role
  namespace: argo
  labels:
    k8s-app: argo
    part-of: argo
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
