---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo
  namespace: argo
  labels:
    k8s-app: argo
    part-of: argo

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-ui
  namespace: argo
  labels:
    k8s-app: argo
    part-of: argo
